name: tasksfidev
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  beamer: ^1.5.3
  riverpod: ^2.1.3
  flutter_riverpod: ^2.1.3
  hooks_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.5.4

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

